generatorName: typescript
templateDir: templates
globalProperties:
  supportingFiles: models/index.ts
  models: ''
files:
  model/index.mustache:
    templateType: SupportingFiles
    destinationFilename: models/index.ts
